import React from "react"
import { Poppins } from "next/font/google"
import BottomBar from "@/components/shared/BottomBar"
import LeftSidebar from "@/components/shared/LeftSidebar"
import Navbar from "@/components/shared/Navbar"
import type { Metadata } from "next"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
})

export const metadata: Metadata = {
  title: "VN Gen Ai",
  description: "Generated by create next app",
}

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <main className={`${poppins.variable}`}>
      <Navbar />
      <main className="flex flex-row">
        <LeftSidebar />
        <section className="main-container">
          <div className="w-full">{children}</div>
        </section>
      </main>
      <BottomBar />
    </main>
  )
}
