import React from "react"
import { Poppins } from "next/font/google"
import type { Metadata } from "next"
import "../globals.css"


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
})

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
}

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <main className={`${poppins.variable}`}>
          <div className="">{children}</div>
    </main>
  )
}
